spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.162.247:3306/word_battle?useSSL=false&serverTimezone=Asia/Shanghai
    username: Harisy
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://8.134.162.247:3306/word_battle?useSSL=false&serverTimezone=Asia/Shanghai
#      username: Harisy
#      password: 123456
#      max-active: 20
#      max-wait: 6000
#      min-idle: 1
#      test-on-borrow: true
#      test-on-return: true



mybatis-plus:
  type-aliases-package: com.example.springboot.pojo
  mapper-locations: classpath*:com/example/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml